name: books_api
description: Books API
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  crypto: ^3.0.2
  dart_frog: ^0.3.0
  encrypt: ^5.0.1
  jaguar_jwt: ^3.0.0
  mongo_dart: ^0.9.1
  

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^4.0.0
